// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cratebase.Infrastructure.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class Initial : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "artists",
                columns: table => new
                {
                    id = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    artist_id = table.Column<Guid>(type: "uuid", nullable: false),
                    name = table.Column<string>(type: "character varying(512)", maxLength: 512, nullable: false),
                    artist_type = table.Column<string>(type: "character varying(8)", maxLength: 8, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_artists", x => x.id);
                    table.UniqueConstraint("artist_id", x => x.artist_id);
                });

            migrationBuilder.CreateTable(
                name: "labels",
                columns: table => new
                {
                    id = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    label_id = table.Column<Guid>(type: "uuid", nullable: false),
                    name = table.Column<string>(type: "character varying(512)", maxLength: 512, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_labels", x => x.id);
                    table.UniqueConstraint("label_id", x => x.label_id);
                });

            migrationBuilder.CreateTable(
                name: "releases",
                columns: table => new
                {
                    id = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    release_id = table.Column<Guid>(type: "uuid", nullable: false),
                    rating = table.Column<int>(type: "integer", nullable: true),
                    title = table.Column<string>(type: "character varying(1024)", maxLength: 1024, nullable: false),
                    cover_image_path = table.Column<string>(type: "character varying(2048)", maxLength: 2048, nullable: true),
                    label_id = table.Column<Guid>(type: "uuid", nullable: true),
                    release_date = table.Column<DateOnly>(type: "date", nullable: true),
                    release_type = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: false),
                    release_year = table.Column<int>(type: "integer", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_releases", x => x.id);
                    table.UniqueConstraint("release_id", x => x.release_id);
                    table.ForeignKey(
                        name: "FK_releases_labels_label_id",
                        column: x => x.label_id,
                        principalTable: "labels",
                        principalColumn: "label_id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "tracks",
                columns: table => new
                {
                    id = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    track_id = table.Column<Guid>(type: "uuid", nullable: false),
                    title = table.Column<string>(type: "character varying(1024)", maxLength: 1024, nullable: false),
                    duration_ticks = table.Column<long>(type: "bigint", nullable: true),
                    rating = table.Column<int>(type: "integer", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_tracks", x => x.id);
                    table.UniqueConstraint("track_id", x => x.track_id);
                });

            migrationBuilder.CreateTable(
                name: "artist_relations",
                columns: table => new
                {
                    id = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    artist_relation_id = table.Column<Guid>(type: "uuid", nullable: false),
                    source_artist_id = table.Column<Guid>(type: "uuid", nullable: false),
                    target_artist_id = table.Column<Guid>(type: "uuid", nullable: false),
                    type = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: false),
                    period_end_year = table.Column<int>(type: "integer", nullable: true),
                    period_start_year = table.Column<int>(type: "integer", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_artist_relations", x => x.id);
                    table.UniqueConstraint("artist_relation_id", x => x.artist_relation_id);
                    table.ForeignKey(
                        name: "FK_artist_relations_artists_source_artist_id",
                        column: x => x.source_artist_id,
                        principalTable: "artists",
                        principalColumn: "artist_id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_artist_relations_artists_target_artist_id",
                        column: x => x.target_artist_id,
                        principalTable: "artists",
                        principalColumn: "artist_id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "release_genres",
                columns: table => new
                {
                    name = table.Column<string>(type: "character varying(256)", maxLength: 256, nullable: false),
                    release_id = table.Column<Guid>(type: "uuid", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_release_genres", x => new { x.release_id, x.name });
                    table.ForeignKey(
                        name: "FK_release_genres_releases_release_id",
                        column: x => x.release_id,
                        principalTable: "releases",
                        principalColumn: "release_id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "release_tags",
                columns: table => new
                {
                    name = table.Column<string>(type: "character varying(256)", maxLength: 256, nullable: false),
                    release_id = table.Column<Guid>(type: "uuid", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_release_tags", x => new { x.release_id, x.name });
                    table.ForeignKey(
                        name: "FK_release_tags_releases_release_id",
                        column: x => x.release_id,
                        principalTable: "releases",
                        principalColumn: "release_id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "credits",
                columns: table => new
                {
                    id = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    credit_id = table.Column<Guid>(type: "uuid", nullable: false),
                    role = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: false),
                    contributor_artist_id = table.Column<Guid>(type: "uuid", nullable: false),
                    contributor_name = table.Column<string>(type: "character varying(1024)", maxLength: 1024, nullable: false),
                    target_release_id = table.Column<Guid>(type: "uuid", nullable: true),
                    target_track_id = table.Column<Guid>(type: "uuid", nullable: true),
                    target_type = table.Column<string>(type: "character varying(32)", maxLength: 32, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_credits", x => x.id);
                    table.UniqueConstraint("credit_id", x => x.credit_id);
                    table.CheckConstraint("ck_credits_target_consistency", "(target_type = 'release' AND target_release_id IS NOT NULL AND target_track_id IS NULL) OR (target_type = 'track' AND target_track_id IS NOT NULL AND target_release_id IS NULL)");
                    table.ForeignKey(
                        name: "FK_credits_artists_contributor_artist_id",
                        column: x => x.contributor_artist_id,
                        principalTable: "artists",
                        principalColumn: "artist_id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_credits_releases_target_release_id",
                        column: x => x.target_release_id,
                        principalTable: "releases",
                        principalColumn: "release_id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_credits_tracks_target_track_id",
                        column: x => x.target_track_id,
                        principalTable: "tracks",
                        principalColumn: "track_id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "owned_items",
                columns: table => new
                {
                    id = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    owned_item_id = table.Column<Guid>(type: "uuid", nullable: false),
                    cassette_tape_type = table.Column<string>(type: "character varying(256)", maxLength: 256, nullable: true),
                    compact_disc_count = table.Column<int>(type: "integer", nullable: true),
                    condition = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: true),
                    digital_file_format = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: true),
                    digital_file_path = table.Column<string>(type: "character varying(4096)", maxLength: 4096, nullable: true),
                    import_identity_content_hash = table.Column<string>(type: "character varying(256)", maxLength: 256, nullable: true),
                    import_identity_last_modified_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    import_identity_path = table.Column<string>(type: "character varying(4096)", maxLength: 4096, nullable: true),
                    import_identity_size_bytes = table.Column<long>(type: "bigint", nullable: true),
                    medium_type = table.Column<string>(type: "character varying(32)", maxLength: 32, nullable: false),
                    other_medium_name = table.Column<string>(type: "character varying(256)", maxLength: 256, nullable: true),
                    ownership_status = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: false),
                    storage_location = table.Column<string>(type: "character varying(512)", maxLength: 512, nullable: true),
                    target_release_id = table.Column<Guid>(type: "uuid", nullable: true),
                    target_track_id = table.Column<Guid>(type: "uuid", nullable: true),
                    target_type = table.Column<string>(type: "character varying(32)", maxLength: 32, nullable: false),
                    vinyl_format_description = table.Column<string>(type: "character varying(256)", maxLength: 256, nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_owned_items", x => x.id);
                    table.UniqueConstraint("owned_item_id", x => x.owned_item_id);
                    table.CheckConstraint("ck_owned_items_target_consistency", "(target_type = 'release' AND target_release_id IS NOT NULL AND target_track_id IS NULL) OR (target_type = 'track' AND target_track_id IS NOT NULL AND target_release_id IS NULL)");
                    table.ForeignKey(
                        name: "FK_owned_items_releases_target_release_id",
                        column: x => x.target_release_id,
                        principalTable: "releases",
                        principalColumn: "release_id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_owned_items_tracks_target_track_id",
                        column: x => x.target_track_id,
                        principalTable: "tracks",
                        principalColumn: "track_id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "release_tracks",
                columns: table => new
                {
                    id = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    track_id = table.Column<Guid>(type: "uuid", nullable: false),
                    position_number = table.Column<int>(type: "integer", nullable: false),
                    position_disc = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: true),
                    position_side = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: true),
                    title_override = table.Column<string>(type: "character varying(1024)", maxLength: 1024, nullable: true),
                    release_id = table.Column<Guid>(type: "uuid", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_release_tracks", x => x.id);
                    table.ForeignKey(
                        name: "FK_release_tracks_releases_release_id",
                        column: x => x.release_id,
                        principalTable: "releases",
                        principalColumn: "release_id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_release_tracks_tracks_track_id",
                        column: x => x.track_id,
                        principalTable: "tracks",
                        principalColumn: "track_id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "track_genres",
                columns: table => new
                {
                    name = table.Column<string>(type: "character varying(256)", maxLength: 256, nullable: false),
                    track_id = table.Column<Guid>(type: "uuid", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_track_genres", x => new { x.track_id, x.name });
                    table.ForeignKey(
                        name: "FK_track_genres_tracks_track_id",
                        column: x => x.track_id,
                        principalTable: "tracks",
                        principalColumn: "track_id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "track_relations",
                columns: table => new
                {
                    id = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    track_relation_id = table.Column<Guid>(type: "uuid", nullable: false),
                    source_track_id = table.Column<Guid>(type: "uuid", nullable: false),
                    target_track_id = table.Column<Guid>(type: "uuid", nullable: false),
                    relation_type = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_track_relations", x => x.id);
                    table.UniqueConstraint("track_relation_id", x => x.track_relation_id);
                    table.ForeignKey(
                        name: "FK_track_relations_tracks_source_track_id",
                        column: x => x.source_track_id,
                        principalTable: "tracks",
                        principalColumn: "track_id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_track_relations_tracks_target_track_id",
                        column: x => x.target_track_id,
                        principalTable: "tracks",
                        principalColumn: "track_id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "track_tags",
                columns: table => new
                {
                    name = table.Column<string>(type: "character varying(256)", maxLength: 256, nullable: false),
                    track_id = table.Column<Guid>(type: "uuid", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_track_tags", x => new { x.track_id, x.name });
                    table.ForeignKey(
                        name: "FK_track_tags_tracks_track_id",
                        column: x => x.track_id,
                        principalTable: "tracks",
                        principalColumn: "track_id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_artist_relations_source_artist_id",
                table: "artist_relations",
                column: "source_artist_id");

            migrationBuilder.CreateIndex(
                name: "IX_artist_relations_target_artist_id",
                table: "artist_relations",
                column: "target_artist_id");

            migrationBuilder.CreateIndex(
                name: "IX_credits_contributor_artist_id",
                table: "credits",
                column: "contributor_artist_id");

            migrationBuilder.CreateIndex(
                name: "IX_credits_role",
                table: "credits",
                column: "role");

            migrationBuilder.CreateIndex(
                name: "IX_credits_target_release_id",
                table: "credits",
                column: "target_release_id");

            migrationBuilder.CreateIndex(
                name: "IX_credits_target_track_id",
                table: "credits",
                column: "target_track_id");

            migrationBuilder.CreateIndex(
                name: "ix_owned_items_import_identity",
                table: "owned_items",
                columns: new[] { "import_identity_path", "import_identity_size_bytes", "import_identity_last_modified_at", "import_identity_content_hash" },
                unique: true,
                filter: "import_identity_path IS NOT NULL")
                .Annotation("Npgsql:NullsDistinct", false);

            migrationBuilder.CreateIndex(
                name: "IX_owned_items_medium_type",
                table: "owned_items",
                column: "medium_type");

            migrationBuilder.CreateIndex(
                name: "IX_owned_items_ownership_status",
                table: "owned_items",
                column: "ownership_status");

            migrationBuilder.CreateIndex(
                name: "IX_owned_items_target_release_id",
                table: "owned_items",
                column: "target_release_id");

            migrationBuilder.CreateIndex(
                name: "IX_owned_items_target_track_id",
                table: "owned_items",
                column: "target_track_id");

            migrationBuilder.CreateIndex(
                name: "IX_releases_label_id",
                table: "releases",
                column: "label_id");

            migrationBuilder.CreateIndex(
                name: "ix_release_tracks_release_id_position",
                table: "release_tracks",
                columns: new[] { "release_id", "position_number", "position_disc", "position_side" },
                unique: true)
                .Annotation("Npgsql:NullsDistinct", false);

            migrationBuilder.CreateIndex(
                name: "IX_release_tracks_track_id",
                table: "release_tracks",
                column: "track_id");

            migrationBuilder.CreateIndex(
                name: "IX_track_relations_source_track_id",
                table: "track_relations",
                column: "source_track_id");

            migrationBuilder.CreateIndex(
                name: "IX_track_relations_target_track_id",
                table: "track_relations",
                column: "target_track_id");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "artist_relations");

            migrationBuilder.DropTable(
                name: "credits");

            migrationBuilder.DropTable(
                name: "owned_items");

            migrationBuilder.DropTable(
                name: "release_genres");

            migrationBuilder.DropTable(
                name: "release_tags");

            migrationBuilder.DropTable(
                name: "release_tracks");

            migrationBuilder.DropTable(
                name: "track_genres");

            migrationBuilder.DropTable(
                name: "track_relations");

            migrationBuilder.DropTable(
                name: "track_tags");

            migrationBuilder.DropTable(
                name: "releases");

            migrationBuilder.DropTable(
                name: "artists");

            migrationBuilder.DropTable(
                name: "labels");

            migrationBuilder.DropTable(
                name: "tracks");
        }
    }
}
