// <auto-generated />
using System;
using System.Collections.Generic;
using Cratebase.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cratebase.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CratebaseDbContext))]
    partial class CratebaseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cratebase.Domain.Catalog.Artist", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("artist_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("name");

                    b.Property<string>("artist_type")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.HasKey("id");

                    b.HasAlternateKey("Id")
                        .HasName("artist_id");

                    b.ToTable("artists", (string)null);

                    b.HasDiscriminator<string>("artist_type").HasValue("Artist");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Cratebase.Domain.Catalog.Label", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("label_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("name");

                    b.HasKey("id");

                    b.HasAlternateKey("Id")
                        .HasName("label_id");

                    b.ToTable("labels", (string)null);
                });

            modelBuilder.Entity("Cratebase.Domain.Catalog.Release", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("release_id");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Summary", "Cratebase.Domain.Catalog.Release.Summary#ReleaseSummary", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int?>("Rating")
                                .HasColumnType("integer")
                                .HasColumnName("rating");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasMaxLength(1024)
                                .HasColumnType("character varying(1024)")
                                .HasColumnName("title");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Metadata", "Cratebase.Domain.Catalog.Release.Summary#ReleaseSummary.Metadata#ReleaseMetadata", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("CoverImage")
                                        .HasMaxLength(2048)
                                        .HasColumnType("character varying(2048)")
                                        .HasColumnName("cover_image_path");

                                    b2.Property<Guid?>("LabelId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("label_id");

                                    b2.Property<DateOnly?>("ReleaseDate")
                                        .HasColumnType("date")
                                        .HasColumnName("release_date");

                                    b2.Property<string>("Type")
                                        .IsRequired()
                                        .HasMaxLength(64)
                                        .HasColumnType("character varying(64)")
                                        .HasColumnName("release_type");

                                    b2.Property<int?>("Year")
                                        .HasColumnType("integer")
                                        .HasColumnName("release_year");
                                });
                        });

                    b.HasKey("id");

                    b.HasAlternateKey("Id")
                        .HasName("release_id");

                    b.ToTable("releases", (string)null);
                });

            modelBuilder.Entity("Cratebase.Domain.Catalog.Track", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("track_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("title");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Details", "Cratebase.Domain.Catalog.Track.Details#TrackDetails", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<long?>("Duration")
                                .HasColumnType("bigint")
                                .HasColumnName("duration_ticks");

                            b1.Property<int?>("Rating")
                                .HasColumnType("integer")
                                .HasColumnName("rating");
                        });

                    b.HasKey("id");

                    b.HasAlternateKey("Id")
                        .HasName("track_id");

                    b.ToTable("tracks", (string)null);
                });

            modelBuilder.Entity("Cratebase.Domain.Collection.OwnedItem", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("owned_item_id");

                    b.Property<string>("_cassetteTapeType")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("cassette_tape_type");

                    b.Property<int?>("_compactDiscCount")
                        .HasColumnType("integer")
                        .HasColumnName("compact_disc_count");

                    b.Property<string>("_condition")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("condition");

                    b.Property<string>("_digitalFileFormat")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("digital_file_format");

                    b.Property<string>("_digitalFilePath")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("digital_file_path");

                    b.Property<string>("_importIdentityContentHash")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("import_identity_content_hash");

                    b.Property<DateTimeOffset?>("_importIdentityLastModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("import_identity_last_modified_at");

                    b.Property<string>("_importIdentityPath")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("import_identity_path");

                    b.Property<long?>("_importIdentitySizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("import_identity_size_bytes");

                    b.Property<string>("_mediumType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("medium_type");

                    b.Property<string>("_otherMediumName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("other_medium_name");

                    b.Property<string>("_status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ownership_status");

                    b.Property<string>("_storageLocation")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("storage_location");

                    b.Property<Guid?>("_targetReleaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_release_id");

                    b.Property<Guid?>("_targetTrackId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_track_id");

                    b.Property<string>("_targetType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("target_type");

                    b.Property<string>("_vinylFormatDescription")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("vinyl_format_description");

                    b.HasKey("id");

                    b.HasAlternateKey("Id")
                        .HasName("owned_item_id");

                    b.HasIndex("_mediumType");

                    b.HasIndex("_status");

                    b.HasIndex("_targetReleaseId");

                    b.HasIndex("_targetTrackId");

                    b.ToTable("owned_items", (string)null);
                });

            modelBuilder.Entity("Cratebase.Domain.Credits.Credit", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("credit_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("role");

                    b.Property<Guid>("_contributorArtistId")
                        .HasColumnType("uuid")
                        .HasColumnName("contributor_artist_id");

                    b.Property<string>("_contributorName")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("contributor_name");

                    b.Property<Guid?>("_targetReleaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_release_id");

                    b.Property<Guid?>("_targetTrackId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_track_id");

                    b.Property<string>("_targetType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("target_type");

                    b.HasKey("id");

                    b.HasAlternateKey("Id")
                        .HasName("credit_id");

                    b.HasIndex("Role");

                    b.HasIndex("_contributorArtistId");

                    b.HasIndex("_targetReleaseId");

                    b.HasIndex("_targetTrackId");

                    b.ToTable("credits", (string)null);
                });

            modelBuilder.Entity("Cratebase.Domain.Relations.ArtistRelation", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("artist_relation_id");

                    b.Property<Guid>("SourceArtistId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_artist_id");

                    b.Property<Guid>("TargetArtistId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_artist_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("type");

                    b.Property<int?>("_periodEndYear")
                        .HasColumnType("integer")
                        .HasColumnName("period_end_year");

                    b.Property<int?>("_periodStartYear")
                        .HasColumnType("integer")
                        .HasColumnName("period_start_year");

                    b.HasKey("id");

                    b.HasAlternateKey("Id")
                        .HasName("artist_relation_id");

                    b.HasIndex("SourceArtistId");

                    b.HasIndex("TargetArtistId");

                    b.ToTable("artist_relations", (string)null);
                });

            modelBuilder.Entity("Cratebase.Domain.Relations.TrackRelation", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("track_relation_id");

                    b.Property<string>("RelationType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("relation_type");

                    b.Property<Guid>("SourceTrackId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_track_id");

                    b.Property<Guid>("TargetTrackId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_track_id");

                    b.HasKey("id");

                    b.HasAlternateKey("Id")
                        .HasName("track_relation_id");

                    b.HasIndex("SourceTrackId");

                    b.HasIndex("TargetTrackId");

                    b.ToTable("track_relations", (string)null);
                });

            modelBuilder.Entity("Cratebase.Domain.Catalog.Group", b =>
                {
                    b.HasBaseType("Cratebase.Domain.Catalog.Artist");

                    b.HasDiscriminator().HasValue("group");
                });

            modelBuilder.Entity("Cratebase.Domain.Catalog.Person", b =>
                {
                    b.HasBaseType("Cratebase.Domain.Catalog.Artist");

                    b.HasDiscriminator().HasValue("person");
                });

            modelBuilder.Entity("Cratebase.Domain.Catalog.Release", b =>
                {
                    b.OwnsMany("Cratebase.Domain.Catalog.Genre", "_genres", b1 =>
                        {
                            b1.Property<Guid>("release_id")
                                .HasColumnType("uuid")
                                .HasColumnName("release_id");

                            b1.Property<string>("Name")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("name");

                            b1.HasKey("release_id", "Name");

                            b1.ToTable("release_genres", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("release_id")
                                .HasPrincipalKey("Id");
                        });

                    b.OwnsMany("Cratebase.Domain.Catalog.Tag", "_tags", b1 =>
                        {
                            b1.Property<Guid>("release_id")
                                .HasColumnType("uuid")
                                .HasColumnName("release_id");

                            b1.Property<string>("Name")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("name");

                            b1.HasKey("release_id", "Name");

                            b1.ToTable("release_tags", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("release_id")
                                .HasPrincipalKey("Id");
                        });

                    b.OwnsMany("Cratebase.Domain.Catalog.ReleaseTrack", "Tracklist", b1 =>
                        {
                            b1.Property<long>("id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<long>("id"));

                            b1.Property<string>("TitleOverride")
                                .HasMaxLength(1024)
                                .HasColumnType("character varying(1024)")
                                .HasColumnName("title_override");

                            b1.Property<Guid>("TrackId")
                                .HasColumnType("uuid")
                                .HasColumnName("track_id");

                            b1.Property<Guid>("release_id")
                                .HasColumnType("uuid")
                                .HasColumnName("release_id");

                            b1.HasKey("id");

                            b1.HasIndex("TrackId");

                            b1.HasIndex("release_id");

                            b1.ToTable("release_tracks", (string)null);

                            b1.HasOne("Cratebase.Domain.Catalog.Track", null)
                                .WithMany()
                                .HasForeignKey("TrackId")
                                .HasPrincipalKey("Id")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("release_id")
                                .HasPrincipalKey("Id");

                            b1.OwnsOne("Cratebase.Domain.Catalog.TrackPosition", "Position", b2 =>
                                {
                                    b2.Property<long>("ReleaseTrackid")
                                        .HasColumnType("bigint");

                                    b2.Property<string>("Disc")
                                        .HasMaxLength(64)
                                        .HasColumnType("character varying(64)")
                                        .HasColumnName("position_disc");

                                    b2.Property<int>("Number")
                                        .HasColumnType("integer")
                                        .HasColumnName("position_number");

                                    b2.Property<string>("Side")
                                        .HasMaxLength(64)
                                        .HasColumnType("character varying(64)")
                                        .HasColumnName("position_side");

                                    b2.HasKey("ReleaseTrackid");

                                    b2.ToTable("release_tracks");

                                    b2.WithOwner()
                                        .HasForeignKey("ReleaseTrackid");
                                });

                            b1.Navigation("Position")
                                .IsRequired();
                        });

                    b.Navigation("Tracklist");

                    b.Navigation("_genres");

                    b.Navigation("_tags");
                });

            modelBuilder.Entity("Cratebase.Domain.Catalog.Track", b =>
                {
                    b.OwnsMany("Cratebase.Domain.Catalog.Genre", "_genres", b1 =>
                        {
                            b1.Property<Guid>("track_id")
                                .HasColumnType("uuid")
                                .HasColumnName("track_id");

                            b1.Property<string>("Name")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("name");

                            b1.HasKey("track_id", "Name");

                            b1.ToTable("track_genres", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("track_id")
                                .HasPrincipalKey("Id");
                        });

                    b.OwnsMany("Cratebase.Domain.Catalog.Tag", "_tags", b1 =>
                        {
                            b1.Property<Guid>("track_id")
                                .HasColumnType("uuid")
                                .HasColumnName("track_id");

                            b1.Property<string>("Name")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("name");

                            b1.HasKey("track_id", "Name");

                            b1.ToTable("track_tags", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("track_id")
                                .HasPrincipalKey("Id");
                        });

                    b.Navigation("_genres");

                    b.Navigation("_tags");
                });

            modelBuilder.Entity("Cratebase.Domain.Collection.OwnedItem", b =>
                {
                    b.HasOne("Cratebase.Domain.Catalog.Release", null)
                        .WithMany()
                        .HasForeignKey("_targetReleaseId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Cratebase.Domain.Catalog.Track", null)
                        .WithMany()
                        .HasForeignKey("_targetTrackId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Cratebase.Domain.Credits.Credit", b =>
                {
                    b.HasOne("Cratebase.Domain.Catalog.Artist", null)
                        .WithMany()
                        .HasForeignKey("_contributorArtistId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cratebase.Domain.Catalog.Release", null)
                        .WithMany()
                        .HasForeignKey("_targetReleaseId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Cratebase.Domain.Catalog.Track", null)
                        .WithMany()
                        .HasForeignKey("_targetTrackId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Cratebase.Domain.Relations.ArtistRelation", b =>
                {
                    b.HasOne("Cratebase.Domain.Catalog.Artist", null)
                        .WithMany()
                        .HasForeignKey("SourceArtistId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cratebase.Domain.Catalog.Artist", null)
                        .WithMany()
                        .HasForeignKey("TargetArtistId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Cratebase.Domain.Relations.TrackRelation", b =>
                {
                    b.HasOne("Cratebase.Domain.Catalog.Track", null)
                        .WithMany()
                        .HasForeignKey("SourceTrackId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cratebase.Domain.Catalog.Track", null)
                        .WithMany()
                        .HasForeignKey("TargetTrackId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
