// <auto-generated />
using System;
using System.Collections.Generic;
using Cratebase.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cratebase.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CratebaseDbContext))]
    partial class CratebaseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cratebase.Domain.Catalog.Artist", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<Guid>("CollectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("collection_id");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("artist_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("name");

                    b.Property<string>("artist_type")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.HasKey("id");

                    b.HasAlternateKey("Id")
                        .HasName("artist_id");

                    b.HasAlternateKey("CollectionId", "Id")
                        .HasName("ak_artists_collection_artist_id");

                    b.HasIndex("CollectionId");

                    b.ToTable("artists", (string)null);

                    b.HasDiscriminator<string>("artist_type").HasValue("Artist");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Cratebase.Domain.Catalog.Label", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<Guid>("CollectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("collection_id");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("label_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("name");

                    b.HasKey("id");

                    b.HasAlternateKey("Id")
                        .HasName("label_id");

                    b.HasAlternateKey("CollectionId", "Id")
                        .HasName("ak_labels_collection_label_id");

                    b.HasIndex("CollectionId");

                    b.ToTable("labels", (string)null);
                });

            modelBuilder.Entity("Cratebase.Domain.Catalog.Release", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<Guid>("CollectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("collection_id");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("release_id");

                    b.Property<bool>("IsNotOnLabel")
                        .HasColumnType("boolean")
                        .HasColumnName("is_not_on_label");

                    b.Property<bool>("IsVariousArtists")
                        .HasColumnType("boolean")
                        .HasColumnName("is_various_artists");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Summary", "Cratebase.Domain.Catalog.Release.Summary#ReleaseSummary", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int?>("Rating")
                                .HasColumnType("integer")
                                .HasColumnName("rating");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasMaxLength(1024)
                                .HasColumnType("character varying(1024)")
                                .HasColumnName("title");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Metadata", "Cratebase.Domain.Catalog.Release.Summary#ReleaseSummary.Metadata#ReleaseMetadata", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("CoverImage")
                                        .HasMaxLength(2048)
                                        .HasColumnType("character varying(2048)")
                                        .HasColumnName("cover_image_path");

                                    b2.Property<Guid?>("LabelId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("label_id");

                                    b2.Property<DateOnly?>("ReleaseDate")
                                        .HasColumnType("date")
                                        .HasColumnName("release_date");

                                    b2.Property<string>("Type")
                                        .IsRequired()
                                        .HasMaxLength(64)
                                        .HasColumnType("character varying(64)")
                                        .HasColumnName("release_type");

                                    b2.Property<int?>("Year")
                                        .HasColumnType("integer")
                                        .HasColumnName("release_year");
                                });
                        });

                    b.HasKey("id");

                    b.HasAlternateKey("Id")
                        .HasName("release_id");

                    b.HasAlternateKey("CollectionId", "Id")
                        .HasName("ak_releases_collection_release_id");

                    b.HasIndex("CollectionId");

                    b.ToTable("releases", (string)null);
                });

            modelBuilder.Entity("Cratebase.Domain.Catalog.Track", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<Guid>("CollectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("collection_id");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("track_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("title");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Details", "Cratebase.Domain.Catalog.Track.Details#TrackDetails", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<long?>("Duration")
                                .HasColumnType("bigint")
                                .HasColumnName("duration_ticks");

                            b1.Property<int?>("Rating")
                                .HasColumnType("integer")
                                .HasColumnName("rating");
                        });

                    b.HasKey("id");

                    b.HasAlternateKey("Id")
                        .HasName("track_id");

                    b.HasAlternateKey("CollectionId", "Id")
                        .HasName("ak_tracks_collection_track_id");

                    b.HasIndex("CollectionId");

                    b.ToTable("tracks", (string)null);
                });

            modelBuilder.Entity("Cratebase.Domain.Collection.MusicCollection", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("collection_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.HasKey("id");

                    b.HasAlternateKey("Id")
                        .HasName("collection_id");

                    b.HasIndex("OwnerUserId")
                        .IsUnique();

                    b.ToTable("collections", (string)null);
                });

            modelBuilder.Entity("Cratebase.Domain.Collection.OwnedItem", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<Guid>("CollectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("collection_id");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("owned_item_id");

                    b.Property<string>("_cassetteTapeType")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("cassette_tape_type");

                    b.Property<int?>("_compactDiscCount")
                        .HasColumnType("integer")
                        .HasColumnName("compact_disc_count");

                    b.Property<string>("_condition")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("condition");

                    b.Property<string>("_digitalFileFormat")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("digital_file_format");

                    b.Property<string>("_digitalFilePath")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("digital_file_path");

                    b.Property<string>("_importIdentityContentHash")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("import_identity_content_hash");

                    b.Property<DateTimeOffset?>("_importIdentityLastModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("import_identity_last_modified_at");

                    b.Property<string>("_importIdentityPath")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("import_identity_path");

                    b.Property<long?>("_importIdentitySizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("import_identity_size_bytes");

                    b.Property<string>("_mediumType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("medium_type");

                    b.Property<string>("_otherMediumName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("other_medium_name");

                    b.Property<string>("_status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ownership_status");

                    b.Property<string>("_storageLocation")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("storage_location");

                    b.Property<Guid?>("_targetReleaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_release_id");

                    b.Property<Guid?>("_targetTrackId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_track_id");

                    b.Property<string>("_targetType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("target_type");

                    b.Property<string>("_vinylFormatDescription")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("vinyl_format_description");

                    b.HasKey("id");

                    b.HasAlternateKey("Id")
                        .HasName("owned_item_id");

                    b.HasIndex("CollectionId");

                    b.HasIndex("_mediumType");

                    b.HasIndex("_status");

                    b.HasIndex("_targetReleaseId");

                    b.HasIndex("_targetTrackId");

                    b.HasIndex("CollectionId", "_targetReleaseId");

                    b.HasIndex("CollectionId", "_targetTrackId");

                    b.HasIndex("CollectionId", "_importIdentityPath", "_importIdentitySizeBytes", "_importIdentityLastModifiedAt", "_importIdentityContentHash")
                        .IsUnique()
                        .HasDatabaseName("ix_owned_items_import_identity")
                        .HasFilter("import_identity_path IS NOT NULL");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("CollectionId", "_importIdentityPath", "_importIdentitySizeBytes", "_importIdentityLastModifiedAt", "_importIdentityContentHash"), false);

                    b.ToTable("owned_items", null, t =>
                        {
                            t.HasCheckConstraint("ck_owned_items_target_consistency", "(target_type = 'release' AND target_release_id IS NOT NULL AND target_track_id IS NULL) OR (target_type = 'track' AND target_track_id IS NOT NULL AND target_release_id IS NULL)");
                        });
                });

            modelBuilder.Entity("Cratebase.Domain.Credits.Credit", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<Guid>("CollectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("collection_id");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("credit_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("role");

                    b.Property<Guid>("_contributorArtistId")
                        .HasColumnType("uuid")
                        .HasColumnName("contributor_artist_id");

                    b.Property<string>("_contributorName")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("contributor_name");

                    b.Property<Guid?>("_targetReleaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_release_id");

                    b.Property<Guid?>("_targetTrackId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_track_id");

                    b.Property<string>("_targetType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("target_type");

                    b.HasKey("id");

                    b.HasAlternateKey("Id")
                        .HasName("credit_id");

                    b.HasIndex("CollectionId");

                    b.HasIndex("Role");

                    b.HasIndex("_contributorArtistId");

                    b.HasIndex("_targetReleaseId");

                    b.HasIndex("_targetTrackId");

                    b.HasIndex("CollectionId", "_contributorArtistId");

                    b.HasIndex("CollectionId", "_targetReleaseId");

                    b.HasIndex("CollectionId", "_targetTrackId");

                    b.ToTable("credits", null, t =>
                        {
                            t.HasCheckConstraint("ck_credits_target_consistency", "(target_type = 'release' AND target_release_id IS NOT NULL AND target_track_id IS NULL) OR (target_type = 'track' AND target_track_id IS NOT NULL AND target_release_id IS NULL)");
                        });
                });

            modelBuilder.Entity("Cratebase.Domain.Relations.ArtistRelation", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<Guid>("CollectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("collection_id");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("artist_relation_id");

                    b.Property<Guid>("SourceArtistId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_artist_id");

                    b.Property<Guid>("TargetArtistId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_artist_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("type");

                    b.Property<int?>("_periodEndYear")
                        .HasColumnType("integer")
                        .HasColumnName("period_end_year");

                    b.Property<int?>("_periodStartYear")
                        .HasColumnType("integer")
                        .HasColumnName("period_start_year");

                    b.HasKey("id");

                    b.HasAlternateKey("Id")
                        .HasName("artist_relation_id");

                    b.HasIndex("CollectionId");

                    b.HasIndex("SourceArtistId");

                    b.HasIndex("TargetArtistId");

                    b.HasIndex("CollectionId", "SourceArtistId");

                    b.HasIndex("CollectionId", "TargetArtistId");

                    b.ToTable("artist_relations", (string)null);
                });

            modelBuilder.Entity("Cratebase.Domain.Relations.TrackRelation", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<Guid>("CollectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("collection_id");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("track_relation_id");

                    b.Property<string>("RelationType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("relation_type");

                    b.Property<Guid>("SourceTrackId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_track_id");

                    b.Property<Guid>("TargetTrackId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_track_id");

                    b.HasKey("id");

                    b.HasAlternateKey("Id")
                        .HasName("track_relation_id");

                    b.HasIndex("CollectionId");

                    b.HasIndex("SourceTrackId");

                    b.HasIndex("TargetTrackId");

                    b.HasIndex("CollectionId", "SourceTrackId");

                    b.HasIndex("CollectionId", "TargetTrackId");

                    b.ToTable("track_relations", (string)null);
                });

            modelBuilder.Entity("Cratebase.Infrastructure.Identity.CratebaseUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<Guid?>("DefaultCollectionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("DefaultCollectionId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Cratebase.Domain.Catalog.Group", b =>
                {
                    b.HasBaseType("Cratebase.Domain.Catalog.Artist");

                    b.HasDiscriminator().HasValue("group");
                });

            modelBuilder.Entity("Cratebase.Domain.Catalog.Person", b =>
                {
                    b.HasBaseType("Cratebase.Domain.Catalog.Artist");

                    b.HasDiscriminator().HasValue("person");
                });

            modelBuilder.Entity("Cratebase.Domain.Catalog.Artist", b =>
                {
                    b.HasOne("Cratebase.Domain.Collection.MusicCollection", null)
                        .WithMany()
                        .HasForeignKey("CollectionId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Cratebase.Domain.Catalog.Label", b =>
                {
                    b.HasOne("Cratebase.Domain.Collection.MusicCollection", null)
                        .WithMany()
                        .HasForeignKey("CollectionId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Cratebase.Domain.Catalog.Release", b =>
                {
                    b.HasOne("Cratebase.Domain.Collection.MusicCollection", null)
                        .WithMany()
                        .HasForeignKey("CollectionId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Cratebase.Domain.Catalog.Genre", "_genres", b1 =>
                        {
                            b1.Property<Guid>("release_id")
                                .HasColumnType("uuid")
                                .HasColumnName("release_id");

                            b1.Property<string>("Name")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("name");

                            b1.HasKey("release_id", "Name");

                            b1.ToTable("release_genres", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("release_id")
                                .HasPrincipalKey("Id");
                        });

                    b.OwnsMany("Cratebase.Domain.Catalog.Tag", "_tags", b1 =>
                        {
                            b1.Property<Guid>("release_id")
                                .HasColumnType("uuid")
                                .HasColumnName("release_id");

                            b1.Property<string>("Name")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("name");

                            b1.HasKey("release_id", "Name");

                            b1.ToTable("release_tags", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("release_id")
                                .HasPrincipalKey("Id");
                        });

                    b.OwnsMany("Cratebase.Domain.Catalog.ReleaseLabel", "Labels", b1 =>
                        {
                            b1.Property<long>("id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<long>("id"));

                            b1.Property<string>("CatalogNumber")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("catalog_number");

                            b1.Property<Guid>("CollectionId")
                                .HasColumnType("uuid")
                                .HasColumnName("collection_id");

                            b1.Property<bool>("HasNoCatalogNumber")
                                .HasColumnType("boolean")
                                .HasColumnName("has_no_catalog_number");

                            b1.Property<Guid>("LabelId")
                                .HasColumnType("uuid")
                                .HasColumnName("label_id");

                            b1.Property<Guid>("release_id")
                                .HasColumnType("uuid")
                                .HasColumnName("release_id");

                            b1.HasKey("id");

                            b1.HasIndex("CollectionId");

                            b1.HasIndex("LabelId");

                            b1.HasIndex("release_id");

                            b1.HasIndex("CollectionId", "LabelId");

                            b1.HasIndex("CollectionId", "release_id");

                            b1.ToTable("release_labels", (string)null, t =>
                                {
                                    t.HasCheckConstraint("ck_release_labels_catalog_number_consistency", "catalog_number IS NULL OR has_no_catalog_number = false");
                                });

                            b1.HasOne("Cratebase.Domain.Catalog.Label", null)
                                .WithMany()
                                .HasForeignKey("CollectionId", "LabelId")
                                .HasPrincipalKey("CollectionId", "Id")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("CollectionId", "release_id")
                                .HasPrincipalKey("CollectionId", "Id");
                        });

                    b.OwnsMany("Cratebase.Domain.Catalog.ReleaseTrack", "Tracklist", b1 =>
                        {
                            b1.Property<long>("id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<long>("id"));

                            b1.Property<Guid>("CollectionId")
                                .HasColumnType("uuid")
                                .HasColumnName("collection_id");

                            b1.Property<string>("TitleOverride")
                                .HasMaxLength(1024)
                                .HasColumnType("character varying(1024)")
                                .HasColumnName("title_override");

                            b1.Property<Guid>("TrackId")
                                .HasColumnType("uuid")
                                .HasColumnName("track_id");

                            b1.Property<string>("VersionNote")
                                .HasMaxLength(2048)
                                .HasColumnType("character varying(2048)")
                                .HasColumnName("version_note");

                            b1.Property<Guid>("release_id")
                                .HasColumnType("uuid")
                                .HasColumnName("release_id");

                            b1.HasKey("id");

                            b1.HasIndex("CollectionId");

                            b1.HasIndex("TrackId");

                            b1.HasIndex("release_id");

                            b1.HasIndex("CollectionId", "TrackId");

                            b1.HasIndex("CollectionId", "release_id");

                            b1.ToTable("release_tracks", (string)null);

                            b1.HasOne("Cratebase.Domain.Catalog.Track", null)
                                .WithMany()
                                .HasForeignKey("CollectionId", "TrackId")
                                .HasPrincipalKey("CollectionId", "Id")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("CollectionId", "release_id")
                                .HasPrincipalKey("CollectionId", "Id");

                            b1.OwnsOne("Cratebase.Domain.Catalog.TrackPosition", "Position", b2 =>
                                {
                                    b2.Property<long>("ReleaseTrackid")
                                        .HasColumnType("bigint");

                                    b2.Property<string>("Disc")
                                        .HasMaxLength(64)
                                        .HasColumnType("character varying(64)")
                                        .HasColumnName("position_disc");

                                    b2.Property<int>("Number")
                                        .HasColumnType("integer")
                                        .HasColumnName("position_number");

                                    b2.Property<string>("Side")
                                        .HasMaxLength(64)
                                        .HasColumnType("character varying(64)")
                                        .HasColumnName("position_side");

                                    b2.HasKey("ReleaseTrackid");

                                    b2.ToTable("release_tracks");

                                    b2.WithOwner()
                                        .HasForeignKey("ReleaseTrackid");
                                });

                            b1.Navigation("Position")
                                .IsRequired();
                        });

                    b.Navigation("Labels");

                    b.Navigation("Tracklist");

                    b.Navigation("_genres");

                    b.Navigation("_tags");
                });

            modelBuilder.Entity("Cratebase.Domain.Catalog.Track", b =>
                {
                    b.HasOne("Cratebase.Domain.Collection.MusicCollection", null)
                        .WithMany()
                        .HasForeignKey("CollectionId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Cratebase.Domain.Catalog.Genre", "_genres", b1 =>
                        {
                            b1.Property<Guid>("track_id")
                                .HasColumnType("uuid")
                                .HasColumnName("track_id");

                            b1.Property<string>("Name")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("name");

                            b1.HasKey("track_id", "Name");

                            b1.ToTable("track_genres", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("track_id")
                                .HasPrincipalKey("Id");
                        });

                    b.OwnsMany("Cratebase.Domain.Catalog.Tag", "_tags", b1 =>
                        {
                            b1.Property<Guid>("track_id")
                                .HasColumnType("uuid")
                                .HasColumnName("track_id");

                            b1.Property<string>("Name")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("name");

                            b1.HasKey("track_id", "Name");

                            b1.ToTable("track_tags", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("track_id")
                                .HasPrincipalKey("Id");
                        });

                    b.Navigation("_genres");

                    b.Navigation("_tags");
                });

            modelBuilder.Entity("Cratebase.Domain.Collection.OwnedItem", b =>
                {
                    b.HasOne("Cratebase.Domain.Collection.MusicCollection", null)
                        .WithMany()
                        .HasForeignKey("CollectionId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cratebase.Domain.Catalog.Release", null)
                        .WithMany()
                        .HasForeignKey("CollectionId", "_targetReleaseId")
                        .HasPrincipalKey("CollectionId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Cratebase.Domain.Catalog.Track", null)
                        .WithMany()
                        .HasForeignKey("CollectionId", "_targetTrackId")
                        .HasPrincipalKey("CollectionId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Cratebase.Domain.Credits.Credit", b =>
                {
                    b.HasOne("Cratebase.Domain.Collection.MusicCollection", null)
                        .WithMany()
                        .HasForeignKey("CollectionId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cratebase.Domain.Catalog.Artist", null)
                        .WithMany()
                        .HasForeignKey("CollectionId", "_contributorArtistId")
                        .HasPrincipalKey("CollectionId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cratebase.Domain.Catalog.Release", null)
                        .WithMany()
                        .HasForeignKey("CollectionId", "_targetReleaseId")
                        .HasPrincipalKey("CollectionId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Cratebase.Domain.Catalog.Track", null)
                        .WithMany()
                        .HasForeignKey("CollectionId", "_targetTrackId")
                        .HasPrincipalKey("CollectionId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Cratebase.Domain.Relations.ArtistRelation", b =>
                {
                    b.HasOne("Cratebase.Domain.Collection.MusicCollection", null)
                        .WithMany()
                        .HasForeignKey("CollectionId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cratebase.Domain.Catalog.Artist", null)
                        .WithMany()
                        .HasForeignKey("CollectionId", "SourceArtistId")
                        .HasPrincipalKey("CollectionId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cratebase.Domain.Catalog.Artist", null)
                        .WithMany()
                        .HasForeignKey("CollectionId", "TargetArtistId")
                        .HasPrincipalKey("CollectionId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Cratebase.Domain.Relations.TrackRelation", b =>
                {
                    b.HasOne("Cratebase.Domain.Collection.MusicCollection", null)
                        .WithMany()
                        .HasForeignKey("CollectionId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cratebase.Domain.Catalog.Track", null)
                        .WithMany()
                        .HasForeignKey("CollectionId", "SourceTrackId")
                        .HasPrincipalKey("CollectionId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cratebase.Domain.Catalog.Track", null)
                        .WithMany()
                        .HasForeignKey("CollectionId", "TargetTrackId")
                        .HasPrincipalKey("CollectionId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Cratebase.Infrastructure.Identity.CratebaseUser", b =>
                {
                    b.HasOne("Cratebase.Domain.Collection.MusicCollection", null)
                        .WithMany()
                        .HasForeignKey("DefaultCollectionId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Cratebase.Infrastructure.Identity.CratebaseUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Cratebase.Infrastructure.Identity.CratebaseUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cratebase.Infrastructure.Identity.CratebaseUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Cratebase.Infrastructure.Identity.CratebaseUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
